---

- name: ulimit -u
  shell: ulimit -u

- name: ulimit -n
  shell: ulimit -n

- name: install iptables
  yum: name=iptables state=present

- name: install iptables-ipv6
  yum: name=iptables-ipv6 state=present

- name: iptables stop chkconfig iptables off
  service: name=iptables state=stopped enabled=no

- name: chkconfig ip6tables off
  service: name=ip6tables state=stopped enabled=no

- name: install libselinux-python
  yum: name=libselinux-python state=present


- name: install selinux
  yum: name={{ item }} state=present
  with_items:
    - libselinux
    - selinux-policy
    - libselinux-python
    - libselinux-utils
    - selinux-policy-targeted


- name: cat /etc/security/limits.d/90-nproc.conf
  shell: cat /etc/security/limits.d/90-nproc.conf

- name: copy 90-nproc.conf
  copy: src=90-nproc.conf dest=/etc/security/limits.d/90-nproc.conf

- name: cat /etc/security/limits.d/90-nproc.conf
  shell: cat /etc/security/limits.d/90-nproc.conf



- name: ulimit -u
  shell: ulimit -u

- name: ulimit -n
  shell: ulimit -n

- name: check SELinux is enforcing
  command: getenforce
  register: selinux_result

- name: disable SELinux with command
  command: setenforce 0
  when: selinux_result == "Enforcing"

- name: disable SELinux config
  lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=disabled

- name: install dependency modules
  yum: name={{item}} state=present
  with_items:
    - sudo
    - tar
    - gcc
    - kernel-devel
    - perl
    - tcl
    - make
    - wget
    - ruby
    - git
    - vim

