---
- name: create /tmp directory on hdfs
  command: hadoop fs -mkdir /tmp

- name: chmod /tmp on hdfs
  command: hadoop fs -chmod -R 1777 /tmp

- name: create /var/log/hadoop-yarn directory on hdfs
  command: hadoop fs -mkdir /var/log/hadoop-yarn

- name: chown /var/log/hadoop-yarn on hdfs
  command: hadoop fs -chown yarn:mapred /var/log/hadoop-yarn

- name: create /tmp/hadoop-yarn/staging directory on hdfs
  command: hadoop fs -mkdir /tmp/hadoop-yarn/staging

- name: chmod /tmp/hadoop-yarn/staging on hdfs
  command: hadoop fs -chmod -R 1777 /tmp/hadoop-yarn/staging

- name: create /tmp/hadoop-yarn/staging/history/done_intermediate directory on hdfs
  command: hadoop fs -mkdir /tmp/hadoop-yarn/staging/history/done_intermediate

- name: chmod /tmp/hadoop-yarn/staging/history/done_intermediate on hdfs
  command: hadoop fs -chmod -R 1777 /tmp/hadoop-yarn/staging/history/done_intermediate

- name: chown /tmp/hadoop-yarn/staging on hdfs
  command: hadoop fs -chown -R mapred:mapred /tmp/hadoop-yarn/staging

- name: mkdir for vagrant user on hdfs
  command: hadoop fs -mkdir /user/vagrant

- name: chown vagrant user directory
  command: hadoop fs -chown vagrant:vagrant /user/vagrant

