---
- name: set Cloudera on yum repository
  template: src=cloudera-cdh4.repo.j2 dest=/etc/yum.repos.d/cloudera-cdh4.repo owner=root group=root mode=0644

# optional
- name: add the Cloudera Public GPG Key
  rpm_key: state=present key=http://archive.cloudera.com/cdh4/redhat/6/x86_64/cdh/RPM-GPG-KEY-cloudera

- name: yum clean all
  shell: yum clean all

- name: install hadoop
  yum: name=hadoop state=present

- name: install pseudo yarn
  yum: name=hadoop-conf-pseudo state=present

- name: copy /etc/hadoop/conf.pseudo to /etc/hadoop/conf.mycluster
  copy: src=/etc/hadoop/conf.pseudo dest=/etc/hadoop/conf.mycluster directory_mode=yes remote_src=True

- name: configure Hadoop in /etc/hadoop/conf.mycluster
  template: src={{ item }}.j2 dest=/etc/hadoop/conf.mycluster/{{ item }} owner=root group=root mode=0644
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - mapred-site.xml
    - yarn-site.xml
    - hadoop-env.sh
    - topology.data

- name: put topology.sh in /etc/hadoop/conf.mycluster (it must be executable)
  template: src={{ item }}.j2 dest=/etc/hadoop/conf.mycluster/{{ item }} owner=root group=root mode=0755
  with_items:
    - topology.sh

- name: run update-alternatives to install hadoop configuration
  alternatives: name=hadoop-conf link=/etc/hadoop/conf path=/etc/hadoop/conf.mycluster

- name: run update-alternatives to set hadoop configuration
  command: update-alternatives --set hadoop-conf /etc/hadoop/conf.mycluster

