---
- hosts: cdh
  remote_user: vagrant
  sudo: yes
  roles:
    - common
    - jdk7
    - cdh_common

- hosts: cdh
  remote_user: vagrant
  sudo: yes
  sudo_user: hdfs
  roles:
    - hadoop_namenode

- hosts: cdh
  remote_user: vagrant
  sudo: yes
  roles:
    - hadoop_start

- hosts: cdh
  remote_user: vagrant
  sudo: yes
  sudo_user: hdfs
  roles:
    - hadoop_hdfs_directory

- hosts: cdh
  remote_user: vagrant
  sudo: yes
  roles:
    - hadoop_start_resourcemanager

