---
- name: install zookeeper-server via yum
  yum: name={{item}} state=present
  with_items:
    - zookeeper
    - zookeeper-server

- name: create /var/lib/zookeeper directory
  file: path=/var/lib/zookeeper owner=zookeeper group=zookeeper state=directory

- name: configure ZooKeeper in /etc/zookeeper/conf.dist
  template: src=zoo.cfg dest=/etc/zookeeper/conf.dist/zoo.cfg owner=zookeeper group=zookeeper mode=0644

- name: initialize ZooKeeper
  command: creates=/var/lib/zookeeper/myid service zookeeper-server init --myid={{zookeeper_id}}

- name: start zookeeper
  command: service zookeeper-server start

